/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "SigmaGrid",
  "tagline": "Institutional fundamentals for 24/7 synthetic-equity perpetuals",
  "url": "https://sigmagrid.app",
  "baseUrl": "/",
  "favicon": "img/logo-mark.svg",
  "organizationName": "sigmagrid",
  "projectName": "sigmagrid-docs",
  "onBrokenLinks": "warn",
  "markdown": {
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    },
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    }
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "plugins": [
    [
      "/home/user/sigmagrid-docs/node_modules/@easyops-cn/docusaurus-search-local/dist/server/server/index.js",
      {
        "hashed": true,
        "language": [
          "en"
        ],
        "indexBlog": false,
        "indexPages": false,
        "docsRouteBasePath": "/docs"
      }
    ]
  ],
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "/home/user/sigmagrid-docs/sidebars.js",
          "routeBasePath": "/docs"
        },
        "blog": false,
        "theme": {
          "customCss": "/home/user/sigmagrid-docs/src/css/custom.css"
        },
        "sitemap": false
      }
    ]
  ],
  "themeConfig": {
    "colorMode": {
      "defaultMode": "dark",
      "disableSwitch": false,
      "respectPrefersColorScheme": false
    },
    "navbar": {
      "title": "SigmaGrid",
      "logo": {
        "alt": "SigmaGrid Logo",
        "src": "img/logo-mark.svg"
      },
      "items": [
        {
          "to": "/docs/intro",
          "label": "Docs",
          "position": "left"
        },
        {
          "to": "/docs/quickstart",
          "label": "Quickstart",
          "position": "left"
        },
        {
          "to": "/docs/api-reference",
          "label": "API Reference",
          "position": "left"
        },
        {
          "to": "/docs/pricing",
          "label": "Pricing",
          "position": "left"
        },
        {
          "href": "https://sigmagrid.app",
          "label": "Main Site",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Product",
          "items": [
            {
              "label": "Overview",
              "to": "/docs/intro"
            },
            {
              "label": "API Reference",
              "to": "/docs/api-reference"
            }
          ]
        },
        {
          "title": "Developers",
          "items": [
            {
              "label": "Quickstart",
              "to": "/docs/quickstart"
            },
            {
              "label": "Fields",
              "to": "/docs/fields"
            },
            {
              "label": "For Agents",
              "to": "/docs/agents"
            }
          ]
        },
        {
          "title": "Meta",
          "items": [
            {
              "label": "llms.txt",
              "href": "pathname:///llms.txt"
            },
            {
              "label": "mcp.json",
              "href": "pathname:///mcp.json"
            },
            {
              "label": "OpenAPI",
              "href": "pathname:///openapi.json"
            },
            {
              "label": "AI Plugin",
              "href": "pathname:///.well-known/ai-plugin.json"
            }
          ]
        }
      ],
      "copyright": "© 2026 SigmaGrid. All rights reserved."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [
        "json"
      ],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "metadata": [
      {
        "name": "description",
        "content": "Traditional equity markets close at 4pm. Crypto synthetic equity perps trade 24/7. Get institutional-grade fair value when Bloomberg terminals go dark. Trusted by AI trading bots, market makers, and crypto hedge funds."
      },
      {
        "name": "og:title",
        "content": "SigmaGrid — Institutional Fair Value for Crypto Perpetual Markets"
      },
      {
        "name": "og:image",
        "content": "img/social-card.svg"
      },
      {
        "name": "twitter:card",
        "content": "summary_large_image"
      },
      {
        "name": "twitter:image",
        "content": "img/social-card.svg"
      }
    ],
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 3
    }
  },
  "headTags": [
    {
      "tagName": "script",
      "attributes": {
        "type": "application/ld+json"
      },
      "innerHTML": "{\"@context\":\"https://schema.org\",\"@type\":\"WebAPI\",\"name\":\"SigmaGrid\",\"description\":\"Institutional fair value for crypto perpetual markets. Traditional equity markets close at 4pm. Crypto synthetic equity perps trade 24/7. Get institutional-grade fair value when Bloomberg terminals go dark.\",\"url\":\"https://sigmagrid.app\",\"documentation\":\"https://sigmagrid.app/docs\",\"provider\":{\"@type\":\"Organization\",\"name\":\"SigmaGrid\",\"url\":\"https://sigmagrid.app\"},\"apiVersion\":\"0.1.0\",\"serviceType\":\"REST API\",\"areaServed\":\"Worldwide\",\"availableChannel\":{\"@type\":\"ServiceChannel\",\"serviceUrl\":\"https://api.sigmagrid.app\",\"availableLanguage\":\"en\"}}"
    }
  ],
  "baseUrlIssueBanner": true,
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": false,
      "useCssCascadeLayers": false
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "themes": [],
  "scripts": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false
};
